# Generated by Django 5.2.11 on 2026-05-04 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='社團名稱')),
                ('max_participants', models.IntegerField(verbose_name='人數上限')),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founded_clubs', to=settings.AUTH_USER_MODEL, verbose_name='社長')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_clubs', to=settings.AUTH_USER_MODEL, verbose_name='指導老師')),
            ],
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '原社長審核中'), (1, '原老師審核中'), (2, '新社長審核中'), (3, '新老師審核中'), (4, '完成')], default=0, verbose_name='進度狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申請時間')),
                ('new_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_requests', to='transfer.club', verbose_name='新社團')),
                ('old_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_requests', to='transfer.club', verbose_name='原社團')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to=settings.AUTH_USER_MODEL, verbose_name='申請人')),
            ],
        ),
    ]
