# Generated by Django 6.0.2 on 2026-05-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_userprofile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, unique=True, verbose_name='社團介紹'),
        ),
    ]
