# Generated by Django 6.0.2 on 2026-05-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0004_club_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrequest',
            name='status',
            field=models.IntegerField(choices=[(0, '原社長審核中'), (1, '原老師審核中'), (2, '新社長審核中'), (3, '新老師審核中'), (4, '完成'), (5, '已退回 (原社長拒絕)'), (6, '已退回 (原老師拒絕)'), (7, '已退回 (新社長拒絕)'), (8, '已退回 (新老師拒絕)')], default=0, verbose_name='進度狀態'),
        ),
    ]
